/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    ArbRwaNft: {
      address: "0xaa292e8611adf267e563f334ee42320ac96d0463",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "owner_",
              type: "address",
            },
            {
              internalType: "address",
              name: "infoDesk_",
              type: "address",
            },
            {
              internalType: "address",
              name: "feeToken_",
              type: "address",
            },
            {
              internalType: "address",
              name: "identityFactory_",
              type: "address",
            },
            {
              internalType: "address",
              name: "claimIssuer_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "contractNft",
              type: "address",
            },
          ],
          name: "ContractNftAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "machineNft",
              type: "address",
            },
          ],
          name: "MachineIssuerAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "regulator",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
          ],
          name: "MachineIssuerRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "machineNft",
              type: "address",
            },
          ],
          name: "MachineNftDeployed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "regulator",
              type: "address",
            },
          ],
          name: "MachineRegulatorAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "regulator",
              type: "address",
            },
          ],
          name: "MachineRegulatorRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          inputs: [],
          name: "addContractNft",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
          ],
          name: "addMachineIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "regulator",
              type: "address",
            },
          ],
          name: "addMachineRegulator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "claimIssuer",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "deployContractNft",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "feeToken",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          name: "findContractNft",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getMachineIssuers",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
          ],
          name: "getMachineNftByIssuer",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "getMachineRegulators",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "identityFactory",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "infoDesk",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          name: "isContractNft",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          name: "isMachineNft",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          name: "isRwaNft",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "contractId",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "contractNft",
              type: "address",
            },
          ],
          name: "registerContractId",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
          ],
          name: "removeMachineIssuer",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "regulator",
              type: "address",
            },
          ],
          name: "removeMachineRegulator",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "issuerOrContractNft",
              type: "address",
            },
            {
              internalType: "bool",
              name: "blocked",
              type: "bool",
            },
          ],
          name: "setMachineNftBlockState",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        addContractNft: "project/contracts/src/interfaces/IArbRwaNft.sol",
        addMachineIssuer: "project/contracts/src/interfaces/IArbRwaNft.sol",
        addMachineRegulator: "project/contracts/src/interfaces/IArbRwaNft.sol",
        findContractNft: "project/contracts/src/interfaces/IArbRwaNft.sol",
        getMachineIssuers: "project/contracts/src/interfaces/IArbRwaNft.sol",
        getMachineNftByIssuer:
          "project/contracts/src/interfaces/IArbRwaNft.sol",
        getMachineRegulators: "project/contracts/src/interfaces/IArbRwaNft.sol",
        isContractNft: "project/contracts/src/interfaces/IArbRwaNft.sol",
        isMachineNft: "project/contracts/src/interfaces/IArbRwaNft.sol",
        isRwaNft: "project/contracts/src/interfaces/IArbRwaNft.sol",
        removeMachineIssuer: "project/contracts/src/interfaces/IArbRwaNft.sol",
        removeMachineRegulator:
          "project/contracts/src/interfaces/IArbRwaNft.sol",
        setMachineNftBlockState:
          "project/contracts/src/interfaces/IArbRwaNft.sol",
        owner: "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
        renounceOwnership:
          "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
        transferOwnership:
          "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
      },
      deployedOnBlock: 98,
    },
    ArbVaultFactory: {
      address: "0x720472c8ce72c2a2d711333e064abd3e6bbeadd3",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "owner_",
              type: "address",
            },
            {
              internalType: "address",
              name: "infoDesk_",
              type: "address",
            },
            {
              internalType: "address",
              name: "trexFactory_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "vault",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "distributor",
              type: "address",
            },
          ],
          name: "VaultCreated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "vault",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "VaultTokenPaused",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "vault",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
          ],
          name: "VaultTokenUnpaused",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "tokenAddr",
              type: "address",
            },
            {
              internalType: "address",
              name: "vaultTaker",
              type: "address",
            },
            {
              internalType: "address",
              name: "asset",
              type: "address",
            },
            {
              internalType: "address[]",
              name: "complianceModules",
              type: "address[]",
            },
          ],
          name: "attachVaultPeers",
          outputs: [
            {
              internalType: "address",
              name: "vaultAddr",
              type: "address",
            },
            {
              internalType: "address",
              name: "distributorAddr",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "vaultTaker",
              type: "address",
            },
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
            {
              internalType: "address",
              name: "asset",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenIdentity",
              type: "address",
            },
            {
              internalType: "address[]",
              name: "claimIssuers",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "claimTopics",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "complianceModules",
              type: "address[]",
            },
          ],
          name: "createVault",
          outputs: [
            {
              internalType: "address",
              name: "vaultAddr",
              type: "address",
            },
            {
              internalType: "address",
              name: "tokenAddr",
              type: "address",
            },
            {
              internalType: "address",
              name: "distributorAddr",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "name",
              type: "string",
            },
            {
              internalType: "string",
              name: "symbol",
              type: "string",
            },
            {
              internalType: "address[]",
              name: "claimIssuers",
              type: "address[]",
            },
            {
              internalType: "uint256[]",
              name: "claimTopics",
              type: "uint256[]",
            },
            {
              internalType: "address[]",
              name: "complianceModules",
              type: "address[]",
            },
          ],
          name: "deployTrexVault",
          outputs: [
            {
              internalType: "address",
              name: "tokenAddr",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "infoDesk",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "vault",
              type: "address",
            },
          ],
          name: "isArbVault",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "vault",
              type: "address",
            },
          ],
          name: "pauseVaultToken",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "infoDesk_",
              type: "address",
            },
          ],
          name: "setInfoDesk",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "trexFactory_",
              type: "address",
            },
          ],
          name: "setTrexFactory",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "trexFactory",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "vault",
              type: "address",
            },
          ],
          name: "unpauseVaultToken",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        createVault: "project/contracts/src/interfaces/IArbVaultFactory.sol",
        isArbVault: "project/contracts/src/interfaces/IArbVaultFactory.sol",
        pauseVaultToken:
          "project/contracts/src/interfaces/IArbVaultFactory.sol",
        unpauseVaultToken:
          "project/contracts/src/interfaces/IArbVaultFactory.sol",
        owner: "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
        renounceOwnership:
          "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
        transferOwnership:
          "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
      },
      deployedOnBlock: 100,
    },
    ClaimIssuer: {
      address: "0x4EE6eCAD1c2Dae9f525404De8555724e3c35d07B",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialManagementKey",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "Approved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
          ],
          name: "ClaimRevoked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "Executed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "ExecutionFailed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "ExecutionRequested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "purpose",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
          ],
          name: "KeyAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "purpose",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
          ],
          name: "KeyRemoved",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_topic",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_scheme",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_issuer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "_signature",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
            {
              internalType: "string",
              name: "_uri",
              type: "string",
            },
          ],
          name: "addClaim",
          outputs: [
            {
              internalType: "bytes32",
              name: "claimRequestId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_type",
              type: "uint256",
            },
          ],
          name: "addKey",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_approve",
              type: "bool",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
          ],
          name: "execute",
          outputs: [
            {
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_claimId",
              type: "bytes32",
            },
          ],
          name: "getClaim",
          outputs: [
            {
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_topic",
              type: "uint256",
            },
          ],
          name: "getClaimIdsByTopic",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "claimIds",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
          ],
          name: "getKey",
          outputs: [
            {
              internalType: "uint256[]",
              name: "purposes",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
          ],
          name: "getKeyPurposes",
          outputs: [
            {
              internalType: "uint256[]",
              name: "_purposes",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "getKeysByPurpose",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "keys",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "sig",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "dataHash",
              type: "bytes32",
            },
          ],
          name: "getRecoveredAddress",
          outputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "initialManagementKey",
              type: "address",
            },
          ],
          name: "initialize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "_sig",
              type: "bytes",
            },
          ],
          name: "isClaimRevoked",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IIdentity",
              name: "_identity",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "claimTopic",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "sig",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "isClaimValid",
          outputs: [
            {
              internalType: "bool",
              name: "claimValid",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "keyHasPurpose",
          outputs: [
            {
              internalType: "bool",
              name: "result",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_claimId",
              type: "bytes32",
            },
          ],
          name: "removeClaim",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "removeKey",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_claimId",
              type: "bytes32",
            },
            {
              internalType: "address",
              name: "_identity",
              type: "address",
            },
          ],
          name: "revokeClaim",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
          ],
          name: "revokeClaimBySignature",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "",
              type: "bytes",
            },
          ],
          name: "revokedClaims",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "version",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    IdentityImplementation: {
      address: "0x2E2Ed0Cfd3AD2f1d34481277b3204d807Ca2F8c2",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "initialManagementKey",
              type: "address",
            },
            {
              internalType: "bool",
              name: "_isLibrary",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bool",
              name: "approved",
              type: "bool",
            },
          ],
          name: "Approved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimChanged",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "claimId",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              indexed: false,
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          name: "ClaimRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "Executed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "ExecutionFailed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
            {
              indexed: false,
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "ExecutionRequested",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "purpose",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
          ],
          name: "KeyAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "purpose",
              type: "uint256",
            },
            {
              indexed: true,
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
          ],
          name: "KeyRemoved",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_topic",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_scheme",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "_issuer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "_signature",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
            {
              internalType: "string",
              name: "_uri",
              type: "string",
            },
          ],
          name: "addClaim",
          outputs: [
            {
              internalType: "bytes32",
              name: "claimRequestId",
              type: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "_type",
              type: "uint256",
            },
          ],
          name: "addKey",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_id",
              type: "uint256",
            },
            {
              internalType: "bool",
              name: "_approve",
              type: "bool",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "_value",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "_data",
              type: "bytes",
            },
          ],
          name: "execute",
          outputs: [
            {
              internalType: "uint256",
              name: "executionId",
              type: "uint256",
            },
          ],
          stateMutability: "payable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_claimId",
              type: "bytes32",
            },
          ],
          name: "getClaim",
          outputs: [
            {
              internalType: "uint256",
              name: "topic",
              type: "uint256",
            },
            {
              internalType: "uint256",
              name: "scheme",
              type: "uint256",
            },
            {
              internalType: "address",
              name: "issuer",
              type: "address",
            },
            {
              internalType: "bytes",
              name: "signature",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
            {
              internalType: "string",
              name: "uri",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_topic",
              type: "uint256",
            },
          ],
          name: "getClaimIdsByTopic",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "claimIds",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
          ],
          name: "getKey",
          outputs: [
            {
              internalType: "uint256[]",
              name: "purposes",
              type: "uint256[]",
            },
            {
              internalType: "uint256",
              name: "keyType",
              type: "uint256",
            },
            {
              internalType: "bytes32",
              name: "key",
              type: "bytes32",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
          ],
          name: "getKeyPurposes",
          outputs: [
            {
              internalType: "uint256[]",
              name: "_purposes",
              type: "uint256[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "getKeysByPurpose",
          outputs: [
            {
              internalType: "bytes32[]",
              name: "keys",
              type: "bytes32[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes",
              name: "sig",
              type: "bytes",
            },
            {
              internalType: "bytes32",
              name: "dataHash",
              type: "bytes32",
            },
          ],
          name: "getRecoveredAddress",
          outputs: [
            {
              internalType: "address",
              name: "addr",
              type: "address",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "initialManagementKey",
              type: "address",
            },
          ],
          name: "initialize",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "contract IIdentity",
              name: "_identity",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "claimTopic",
              type: "uint256",
            },
            {
              internalType: "bytes",
              name: "sig",
              type: "bytes",
            },
            {
              internalType: "bytes",
              name: "data",
              type: "bytes",
            },
          ],
          name: "isClaimValid",
          outputs: [
            {
              internalType: "bool",
              name: "claimValid",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "keyHasPurpose",
          outputs: [
            {
              internalType: "bool",
              name: "result",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_claimId",
              type: "bytes32",
            },
          ],
          name: "removeClaim",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "bytes32",
              name: "_key",
              type: "bytes32",
            },
            {
              internalType: "uint256",
              name: "_purpose",
              type: "uint256",
            },
          ],
          name: "removeKey",
          outputs: [
            {
              internalType: "bool",
              name: "success",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "version",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "pure",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    IdFactory: {
      address: "0xDC11f7E700A4c898AE5CAddB1082cFfa76512aDD",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "implementationAuthority",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "_addr",
              type: "address",
            },
          ],
          name: "Deployed",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "factory",
              type: "address",
            },
          ],
          name: "TokenFactoryAdded",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "factory",
              type: "address",
            },
          ],
          name: "TokenFactoryRemoved",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "token",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "identity",
              type: "address",
            },
          ],
          name: "TokenLinked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "identity",
              type: "address",
            },
          ],
          name: "WalletLinked",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "wallet",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "identity",
              type: "address",
            },
          ],
          name: "WalletUnlinked",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_factory",
              type: "address",
            },
          ],
          name: "addTokenFactory",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_wallet",
              type: "address",
            },
            {
              internalType: "string",
              name: "_salt",
              type: "string",
            },
          ],
          name: "createIdentity",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_wallet",
              type: "address",
            },
            {
              internalType: "string",
              name: "_salt",
              type: "string",
            },
            {
              internalType: "bytes32[]",
              name: "_managementKeys",
              type: "bytes32[]",
            },
          ],
          name: "createIdentityWithManagementKeys",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_token",
              type: "address",
            },
            {
              internalType: "address",
              name: "_tokenOwner",
              type: "address",
            },
            {
              internalType: "string",
              name: "_salt",
              type: "string",
            },
          ],
          name: "createTokenIdentity",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_wallet",
              type: "address",
            },
          ],
          name: "getIdentity",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_identity",
              type: "address",
            },
          ],
          name: "getToken",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_identity",
              type: "address",
            },
          ],
          name: "getWallets",
          outputs: [
            {
              internalType: "address[]",
              name: "",
              type: "address[]",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "implementationAuthority",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_salt",
              type: "string",
            },
          ],
          name: "isSaltTaken",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_factory",
              type: "address",
            },
          ],
          name: "isTokenFactory",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_newWallet",
              type: "address",
            },
          ],
          name: "linkWallet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_factory",
              type: "address",
            },
          ],
          name: "removeTokenFactory",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_oldWallet",
              type: "address",
            },
          ],
          name: "unlinkWallet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    ImplementationAuthority: {
      address: "0xD8a5a9b31c3C0232E196d518E89Fd8bF83AcAd43",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "implementation",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "address",
              name: "newAddress",
              type: "address",
            },
          ],
          name: "UpdatedImplementation",
          type: "event",
        },
        {
          inputs: [],
          name: "getImplementation",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "_newImplementation",
              type: "address",
            },
          ],
          name: "updateImplementation",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
    },
    InfoDesk: {
      address: "0x36b58f5c1969b7b6591d752ea6f5486d069010ab",
      abi: [
        {
          inputs: [
            {
              internalType: "address",
              name: "owner_",
              type: "address",
            },
          ],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "contractType",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "address",
              name: "oldAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "newAddress",
              type: "address",
            },
          ],
          name: "ContractUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "implementationType",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "address",
              name: "oldAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "newAddress",
              type: "address",
            },
          ],
          name: "ImplementationUpdated",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "previousOwner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "OwnershipTransferred",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: false,
              internalType: "uint8",
              name: "precompileType",
              type: "uint8",
            },
            {
              indexed: false,
              internalType: "address",
              name: "oldAddress",
              type: "address",
            },
            {
              indexed: false,
              internalType: "address",
              name: "newAddress",
              type: "address",
            },
          ],
          name: "PrecompileUpdated",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner_",
              type: "address",
            },
          ],
          name: "InfoDesk_init",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "machineValue",
              type: "uint256",
            },
          ],
          name: "computeMachineRegistrationFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "computeTransactionFee",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "accountType",
              type: "uint8",
            },
          ],
          name: "getAccount",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "contractType",
              type: "uint8",
            },
          ],
          name: "getContract",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "implementationType",
              type: "uint8",
            },
          ],
          name: "getImplementation",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "precompileType",
              type: "uint8",
            },
          ],
          name: "getPrecompile",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "valueType",
              type: "uint8",
            },
          ],
          name: "getValue",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "owner",
          outputs: [
            {
              internalType: "address",
              name: "",
              type: "address",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "renounceOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "resetToDefaults",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "accountType",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "newAccount",
              type: "address",
            },
          ],
          name: "setAccount",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "contractType",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "newAddress",
              type: "address",
            },
          ],
          name: "setContract",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "implementationType",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "newImplementation",
              type: "address",
            },
          ],
          name: "setImplementation",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "precompileType",
              type: "uint8",
            },
            {
              internalType: "address",
              name: "newAddress",
              type: "address",
            },
          ],
          name: "setPrecompile",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "uint8",
              name: "valueType",
              type: "uint8",
            },
            {
              internalType: "uint256",
              name: "newValue",
              type: "uint256",
            },
          ],
          name: "setValue",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "newOwner",
              type: "address",
            },
          ],
          name: "transferOwnership",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        InfoDesk_init: "project/contracts/src/interfaces/IInfoDesk.sol",
        computeMachineRegistrationFee:
          "project/contracts/src/interfaces/IInfoDesk.sol",
        computeTransactionFee: "project/contracts/src/interfaces/IInfoDesk.sol",
        getAccount: "project/contracts/src/interfaces/IInfoDesk.sol",
        getContract: "project/contracts/src/interfaces/IInfoDesk.sol",
        getImplementation: "project/contracts/src/interfaces/IInfoDesk.sol",
        getPrecompile: "project/contracts/src/interfaces/IInfoDesk.sol",
        getValue: "project/contracts/src/interfaces/IInfoDesk.sol",
        resetToDefaults: "project/contracts/src/interfaces/IInfoDesk.sol",
        setAccount: "project/contracts/src/interfaces/IInfoDesk.sol",
        setContract: "project/contracts/src/interfaces/IInfoDesk.sol",
        setImplementation: "project/contracts/src/interfaces/IInfoDesk.sol",
        setPrecompile: "project/contracts/src/interfaces/IInfoDesk.sol",
        setValue: "project/contracts/src/interfaces/IInfoDesk.sol",
        owner: "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
        renounceOwnership:
          "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
        transferOwnership:
          "npm/@openzeppelin/contracts@4.9.6/access/Ownable.sol",
      },
      deployedOnBlock: 76,
    },
    MockFeeToken: {
      address: "0x51a1ceb83b83f1985a81c295d1ff28afef186e02",
      abi: [
        {
          inputs: [],
          stateMutability: "nonpayable",
          type: "constructor",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Approval",
          type: "event",
        },
        {
          anonymous: false,
          inputs: [
            {
              indexed: true,
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              indexed: true,
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              indexed: false,
              internalType: "uint256",
              name: "value",
              type: "uint256",
            },
          ],
          name: "Transfer",
          type: "event",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "owner",
              type: "address",
            },
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
          ],
          name: "allowance",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "approve",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "account",
              type: "address",
            },
          ],
          name: "balanceOf",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "decimals",
          outputs: [
            {
              internalType: "uint8",
              name: "",
              type: "uint8",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "subtractedValue",
              type: "uint256",
            },
          ],
          name: "decreaseAllowance",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "spender",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "addedValue",
              type: "uint256",
            },
          ],
          name: "increaseAllowance",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "mint",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [],
          name: "name",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "symbol",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "totalSupply",
          outputs: [
            {
              internalType: "uint256",
              name: "",
              type: "uint256",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "transfer",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "address",
              name: "from",
              type: "address",
            },
            {
              internalType: "address",
              name: "to",
              type: "address",
            },
            {
              internalType: "uint256",
              name: "amount",
              type: "uint256",
            },
          ],
          name: "transferFrom",
          outputs: [
            {
              internalType: "bool",
              name: "",
              type: "bool",
            },
          ],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {
        allowance: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        approve: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        balanceOf: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        decimals: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        decreaseAllowance:
          "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        increaseAllowance:
          "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        name: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        symbol: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        totalSupply: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        transfer: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
        transferFrom: "npm/@openzeppelin/contracts@4.9.6/token/ERC20/ERC20.sol",
      },
      deployedOnBlock: 75,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
